---
aws_region: eu-central-1
aws_keypair_name: id_rsa_laptop_lux
aws_ami_name: ami-04928c5fa611e89b4
aws_instance_type: t2.micro
aws_security_groups: ssh-22-only
ssh_username: ubuntu
ssh_private_key_path: ~/.ssh/id_rsa